<?php
return array (
  'ZC_SITE_TURNOFF' => false,
  'ZC_DATABASE_TYPE' => 'mysqli',
  'ZC_SQLITE_NAME' => '',
  'ZC_SQLITE_PRE' => 'zbp_',
  'ZC_MYSQL_SERVER' => '10.66.150.219',
  'ZC_MYSQL_USERNAME' => 'root',
  'ZC_MYSQL_PASSWORD' => 'songyang@0',
  'ZC_MYSQL_NAME' => 'cuncin',
  'ZC_MYSQL_CHARSET' => 'utf8',
  'ZC_MYSQL_PRE' => 'tc_',
  'ZC_MYSQL_ENGINE' => 'MyISAM',
  'ZC_MYSQL_PORT' => '3306',
  'ZC_MYSQL_PERSISTENT' => false,
  'ZC_PGSQL_SERVER' => 'localhost',
  'ZC_PGSQL_USERNAME' => 'postgres',
  'ZC_PGSQL_PASSWORD' => '',
  'ZC_PGSQL_NAME' => '',
  'ZC_PGSQL_CHARSET' => 'utf8',
  'ZC_PGSQL_PRE' => 'zbp_',
  'ZC_PGSQL_PORT' => '5432',
  'ZC_PGSQL_PERSISTENT' => false,
  'ZC_YUN_SITE' => '',
)
?>